### ISSUE TITLE
Remove `spaceWidth` and `indentation`?

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#107]
Justification for removing SwiftLint https://github.com/CreateAPI/CreateAPI/pull/103 was that the developer should continue post-processing with their own linter. I think we can further follow this idea by dropping these config options and just generating with 4 space indentation (which is usual throughout the field).

**Comment by liamnichols** [comment]
I think there’s a bit of a difference for the motivations here.

Keep in mind the differences between using a linter to detect and warn about issues and using a linter to fix those issues. 

Removing the swiftlint disable comment is about not picking a favourite and making assumptions. Since all linters (to my knowledge) offer a separate mechanism for excluding files/directories, the comment is redundant (hence the motivation to remove it given that you can also add it to the header comment anyway if you wanted). 

While we do have to draw a line about what formatting styles we do apply vs what should be left to a linter, I think indentation style is a pretty foundational one that can remain. 

For example, an Xcode Project also contains a project wide configuration for the preference that is applied when editing, but it doesn’t go further than that with things like customisable parameter alignment and other rules common to third party linters.

**Comment by LePips** [comment]
Firstly, I only brought this up because of the implementation since I recently saw it and could probably just clean it up. We're passing in the options as a parameter to the write function and only using those options to detect the spacing. Small but could be cleaned up.

> linter to fix those issues

In my opinion and experience, teams will have the defined spacing in their linter and autocorrect for that if they care. Removing the swiftlint comment meant that now that the generator should not control _any_ linting and that it is entirely up to the developer to post-process. I think this should be extended to these two options as well due to that justification (and removing two options for cleanliness).

> Xcode Project also contains a project wide configuration for the preference

This is entirely personal to the developer as an IDE option and they furthermore match these options to their linter. Should a _generator_ necessarily care about that as well?

**Comment by kean** [comment]
I think you can live with any other formatting choices made by CreateAPI, but tabs/spaces is fundamental and I've personally seen teams who use 3 spaces. And it's also already implemented in a clean way. But it might be worth "hiding" these options somewhere deeper in the configuration.

**Comment by LePips** [comment]
Alright, well this was just a thought. If we want to "hide" these, we can create a `formatting` section:
```yaml
formatting:
  indentation: tabs
  spaceWidth: 4
  
# or with array/single value checking

formatting:
  indentation:
    spaces: 4
```
