### ISSUE TITLE
Homebrew Installation

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#69]
I rather prefer Homebrew to install all my packages instead over Mint and of course over manual installation for every update. Could there be a Homebrew option for installation?

**Comment by liamnichols** [comment]
Generally speaking, this would be a good idea especially because it would help improve adoption of the tool. 

--- 

Out of curiosity for your specific use case though, is a Swift Package Plugin something that might work out well for you? You can check out one implementation here: AvdLee/appstoreconnect-swift-sdk#191 

I'm also actively looking at other plugin-based workflows that might be useful for CreateAPI users over in #48.

**Comment by LePips** [comment]
I personally haven't used a Swift Package Plugin yet but definitely take a look at it!

**Comment by LePips** [comment]
Additionally, I think a `--version` flag needs to be added.

**Comment by liamnichols** [comment]
> Additionally, I think a `--version` flag needs to be added.

👍 Yep that would be useful! I think swift-argument-parser has support built in, we just need to set it on the `CommandConfiguration` iirc

**Comment by liamnichols** [comment]
0.0.5 is now available via Homebrew! Thanks for the suggestion 

https://formulae.brew.sh/formula/create-api

```
➜ brew install create-api
==> Downloading https://ghcr.io/v2/homebrew/core/create-api/manifests/0.0.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/create-api/blobs/sha256:99d2635
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Pouring create-api--0.0.5.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/create-api/0.0.5: 6 files, 9.1MB
==> Running `brew cleanup create-api`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜ create-api generate --help
USAGE: create-api generate [<options>] <input>
```
