### ISSUE TITLE
Config Options Documentation

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#70]
Apologies as I was a bit too late to leave a comment in https://github.com/CreateAPI/CreateAPI/pull/52, but I would like to propose some improvements to the `ConfigOptions.md` generation since I do reference it a bit.

1 - Alphabetize options within their scope (general, `comments`, `entities`, etc.), but leave sections at the end, sorted by section name.
2 - Add examples under a dropdown
3 - Add dividers to be more easy on the eyes

I'm referencing [SwiftFormat's Rules.md](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md) for these changes as I personally think they present their list of options well.

This issue could have `help-wanted` for the examples on the PR if this is approved as a change.

**Comment by liamnichols** [comment]
Thanks for raising this! I rushed to merge it all up to get the 0.0.5 release out but I agree with your feedback and using SwiftFormat for inspiration is a great idea 👍 

> Alphabetize options within their scope (general, `comments`, `entities`, etc.), but leave sections at the end, sorted by section name.

Makes sense. I did have a concern that maybe we'd want to create related options together, but we can instead just link to them using their anchor so that's fine 👍 

This can be done by manually reordering the contents of **CreateOptions.swift**

> Add examples under a dropdown

Oooh great idea! 

> Add dividers to be more easy on the eyes

Yes, I love this!

--- 

Since I started it, I'll tweak the template to add the dividers, reorder the properties and add a couple of examples for reference but we can leave a [help wanted](https://github.com/CreateAPI/CreateAPI/labels/help%20wanted) issue open for adding to it 👍

**Comment by liamnichols** [comment]
On the other hand actually, sorting alphabetically looks a little worse than I thought:

- **access**
- **addedAcronyms**
- **fileHeaderComment**
- **ignoredAcronyms**
- **indentation**
- **isAddingDeprecations**
- **isGeneratingEnums**
- **isGeneratingSwiftyBooleanPropertyNames**
- **isInliningTypealiases**
- **isNaiveDateEnabled**
- **isPluralizationEnabled**
- **isReplacingCommonAcronyms**
- **isSwiftLintDisabled**
- **isUsingIntegersWithPredefinedCapacity**
- **spaceWidth**

I'm not sure if I'm a fan on having things like `addedAcronyms` and `ignoredAcronyms` separated, same with `indentation` and `spaceWidth`.

Similarly, all of the boolean `isXXX` properties get grouped together and I'm not sure if that's useful or not. 

WDYT?

**Comment by LePips** [comment]
Ah, tt makes sense that related properties being separated is an issue and I didn't think about that. I actually brought up alphabetized sorting because of `isXXX` since there are quite a few. I'd overall be fine without the sorting.

**Comment by liamnichols** [comment]
I'll close this ticket since the main changes were made. If there are particular options that you think should have better Examples added to them, please can you open a Pull Request, or alternatively a ticket if it needs some prior discussion 🙏 

Thanks again!
