### ISSUE TITLE
Remove option `isSwiftLintDisabled`?

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#94]
While it could sometimes be considered a useful feature, I have to slight concerns with it:

1. It assumes we use SwiftLint, but what about other tools?
2. It's more efficient to use a **.swiftlint.yml** configuration to setup `ignore` rules for the generated output directory.
3. If we want it, we could just add it to `fileHeaderComment` instead.

Any other reasons to keep it? I'm suggesting that we either:

1. Remove `isSwiftLintDisabled` with no replacement
2. Remove `isSwiftLintDisabled` but add `// swiftlint:disable all` into the `fileHeaderComment`

Keen to hear what others think.

**Comment by LePips** [comment]
I personally thought this was weird as well. With the discussion from this thread, https://github.com/CreateAPI/CreateAPI/pull/82#discussion_r936799801, we should leave it up to the developer to do whatever linting since they will probably edit it themselves to do post-processing. I personally will be with SwiftFormat.
